"""empty message

Revision ID: 42c26f5efc33
Revises: 
Create Date: 2024-03-15 14:11:02.480902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c26f5efc33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_users_table')),
    sa.UniqueConstraint('id', name=op.f('uq_users_table_id'))
    )
    op.create_table('items_table',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users_table.email'], name=op.f('fk_items_table_user_email_users_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items_table'))
    )
    op.create_table('accounts_table',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items_table.id'], name=op.f('fk_accounts_table_item_id_items_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts_table'))
    )
    op.create_table('transactions_table',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('authorized_date', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('is_removed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts_table.id'], name=op.f('fk_transactions_table_account_id_accounts_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.email'], name=op.f('fk_transactions_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_table')
    op.drop_table('accounts_table')
    op.drop_table('items_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
