"""empty message

Revision ID: 55fc53723bf3
Revises: 42c26f5efc33
Create Date: 2024-03-15 14:11:48.512649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fc53723bf3'
down_revision = '42c26f5efc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_column('users_table', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.drop_column('users_table', 'password_hash')
    # ### end Alembic commands ###
